# Generated by Django 5.0.1 on 2024-04-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('createdate', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('Priority', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
            ],
        ),
    ]
