# Generated by Django 5.0.1 on 2024-04-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmodule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='createdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
