# Generated by Django 5.0.1 on 2024-05-05 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmodule', '0002_alter_task_createdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
