# Generated by Django 5.0.1 on 2024-05-11 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmodule', '0005_checklist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckList',
        ),
    ]
