# Generated by Django 5.0.1 on 2024-05-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmodule', '0007_checklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='done',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
