# Generated by Django 5.0.1 on 2024-05-17 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmodule', '0009_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmodule.task'),
        ),
    ]
